### ISSUE TITLE
Should Polynomials subtype Number ?

### ISSUE THREAD

**Issue by saolof** [JuliaMath/Polynomials.jl#173]
When working with matrices of polynomials (in the context of integrable models / finding solutions to the Yang-Baxter equation), I frequently found myself having to extend standard library methods to work with polynomials.

Polynomials form a commutative ring. They are not weirder than Grassman numbers. Wouldn't it technically make sense to make them an instance of Number in order to make all the standard library methods work? Or export a PolynomialNumber wrapper type that behaves just like a polynomial except for having a different supertype?

**Comment by jverzani** [comment]
I personally don't see why not. It only required adding a method for `IteratorSize`. I'll leave #174 open for a bit, in case others see an issue.

**Comment by olof3** [comment]
I discussed a very similar question at https://gitter.im/JuliaOpt/JuMP-dev, where I wondered if it would make sense to have `AbstractJuMPScalar <: Number` but I was semi-convinced of that it was not such a good idea, the conclusion from that discussion was rather that functions that only accept numbers should be made more general. For example, `Poly` should accept more than `AbstractVector{<:Number}` so that a polynomial can have coefficients of types like `AbstractJuMPScalar`. 

Would probably be good if someone with a good grasp of the Julian design philosophy took a look at this, would be interesting to know how one should reason about this.

**Comment by jverzani** [comment]
I closed a PR that implemented this, as there were some concerns expressed about how it would stand  out among the `Number` sub types. Closing for now.
