### ISSUE TITLE
Feature request: Will you consider adding functions for finding local minima?

### ISSUE THREAD

**Issue by singularitti** [JuliaMath/Polynomials.jl#454]
It does not have to be too complicated. For a finite-order polynomial, take its derivative and find its zeros. I am done it by myself [here](https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/blob/e2924427a76d4816675dc040b2bab145c9adf833/src/Fitting/poly.jl#L4-L37).

**Comment by jverzani** [comment]
Yeah, it is a nice exercise for Polynomials, but I'm a bit wary of adding such a feature, because floating point issues make it a bit unreliable. Here is a slightly different way of doing it using the first derivative test, and there are two places with potential issues. But perhaps, we could extend `findmin`, which would take advantage of this kind of computation, and use something like the following internally.

```
function find_localmin(p::Polynomial{T}, δ = sqrt(eps(float(T)))) where {T}

    p′ = derivative(p)
    real_roots = real.(filter(isreal, roots(p′)))  # <---
    isempty(real_roots) && return real_roots

    Δ = minimum(diff(real_roots)) / 2

    n, aₙ = degree(p), p[end]
    lsgn = ifelse(iseven(n), 1, -1) * sign(aₙ)

    rts = similar(real_roots, 0)

    for r ∈ real_roots
        rsgn = sign(p′(r + Δ))
        lsgn < -δ && rsgn > δ && push!(rts, r)  # <---
        sgn = sgn′
    end

    rts
end
```

**Comment by jverzani** [comment]
I have a pr for `findmin(p, domain=(-Inf, Inf))`. At first, it was using the first-derivative test to classify, but in hindsight that just makes more work than a brute force check over all critical points. If you want the code to find those critical points, let me know.

**Comment by singularitti** [comment]
I like your second & third implementations. They look much better than the first one.

**Comment by jverzani** [comment]
Closing this with #458. I never got around to documenting the difference in #459, if you want to add a PR for that, please do. Thank for the ideas here.
