### ISSUE TITLE
`ImmutablePolynomial` constructors seem to prevent good type inference

### ISSUE THREAD

**Issue by nsajko** [JuliaMath/Polynomials.jl#510]
The variable name and length type parameters are not inferred unless provided explicitly:
```julia-repl
julia> @inferred ImmutablePolynomial((3,))
ERROR: return type ImmutablePolynomial{Int64, :x, 1} does not match inferred return type ImmutablePolynomial{Int64}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[10]:1

julia> @inferred ImmutablePolynomial{Int,:x}((3,))
ERROR: return type ImmutablePolynomial{Int64, :x, 1} does not match inferred return type ImmutablePolynomial{Int64, :x}
```

**Comment by jverzani** [comment]
The `ImmutablePolynomial` type stores the length as a parameter, which due to how the constructor is set up may not be determined from the length of the tuple (as it trims off trailing zeros).

I'm working on a (too-large) PR which changes this type so that it can be inferred (leaving the trimming to the user). The current WIP has

```
julia> @inferred ImmutableDensePolynomial{StandardBasis}((3,))
ImmutableDensePolynomial(3)
```

If things go to plan, `ImmutablePolynomial` will be an alias for `ImmutableDensePolynomial{StandardBasis}` so this should be non breaking.

**Comment by nsajko** [comment]
Oh, trailing zero coefficients actually hadn't occured to me as a possibility. In that case, throwing a `MethodError` here seems like a bug:
```julia-repl
julia> ImmutablePolynomial{Int,:x,1}((1,0))
ERROR: MethodError: no method matching ImmutablePolynomial{Int64, :x, 1}(::Tuple{Int64, Int64})
```

Nice to hear about the upcoming improvements!

**Comment by nsajko** [comment]
> seems like a bug

Well, it's not a bug if the trimming is left to the user, as is intended with the upcoming PR.

**Comment by jverzani** [comment]
This one will work with the new efforts:

```
julia> ImmutableDensePolynomial{StandardBasis,Int,:x,1}((1,0))
ImmutableDensePolynomial(1)
```

(I really appreciate the different cases you are coming up with!)
